engines:
  duplication:
    enabled: false
    config:
      languages: -javascript
  eslint:
    enabled: true
    checks:
      similar-code:
        enabled: false
exclude_patterns:
  - "node_modules/"
  - ".nyc_output"
  - "coverage"
  - "API/lib/*.test.js"
