language: node_js
node_js:
  - "stable"
install:
  - "npm install"
test:
  - "npm test"
cache:
  directories:
    - "node_modules"
after_success:
  - npm run test-dev
  - npm run coveralls | node ./node_modules/coveralls/bin/coveralls.js
  - ./node_modules/.bin/mocha ./API/lib/tests/*.test.js -R mocha-lcov-reporter | node ./node_modules/coveralls/bin/coveralls.js
