language: node_js
node_js:
  - "stable"
install:
  - "npm install"
test:
  - "npm test"
cache:
  directories:
    - "node_modules"
after_success:
  - npm run test-dev
addons:
  code_climate:
    repo_token: <supersecrettoken>
before_script:
  - npm install codeclimate-test-reporter istanbul -g
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
