language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
after_success:
  - npm run coveralls
  - ./node_modules/.bin/jscoverage lib lib-cov
  - ./node_modules/.bin/mocha ./lib/tests/*.test.js -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js
