language: node_js
node_js:
  - "stable"
install:
  - "npm install"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
test:
  - "npm test"
cache:
  directories:
    - "node_modules"
script:
  - npm run test-dev
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
  - npm run test-dev
